stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd /home/vagrant/app
    - docker build -t app:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA} .
    - echo build completed
  rules:
    - if: $CI_COMMIT_TAG != null

deploy:
  stage: deploy
  script:
    - cd /home/vagrant/courses-config
    - |
      sed -i `s/image: app:.*/image: app:'"${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"'/g` deployment.yaml
    - git commit -a -m "Update image to ${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - git push
    - echo complete push
    - kind load docker-image app:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
    - echo load image to cluster
  rules:
    - if: $CI_COMMIT_TAG != null
    - when: manual
