stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t app:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA} .
    - echo build completed
  rules:
    - if: $CI_COMMIT_TAG != null

commit_new_version:
  stage: deploy
  dependencies:
    - build
  script:
    - cd $CONFIG_DIR
    - git pull
    - |
      sed -i 's/image: app:.*/image: app:'"${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"'/g' deployment.yaml
    - git commit -a -m "Update image to ${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - git push
    - echo complete push
  when: manual

load_image:
  stage: deploy
  needs:
    - job: commit_new_version
  script:
    - kind load docker-image app:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
    - echo load image to cluster
